### ISSUE TITLE
Integration: Depth Camera

### ISSUE THREAD

**Issue by wesfletch** [RoboticsClubatUCF/UNTITLED_UGV#15]
Get data from the selected depth camera in a ROS-acceptable data format. Stereolabs provides a ROS node for this specifically, so just get that working and document how.

**Comment by nashirj** [comment]
In today's meeting, we updated the Jettson and installed the most recent SDK for the ZED camera (the Jettson has CUDA 10.0, so we installed the [corresponding sdk](https://download.stereolabs.com/zedsdk/3.6/jp43/jetsons)). We also installed the [zed-ros-wrapper](https://github.com/stereolabs/zed-ros-wrapper) which allows us to run ROS nodes that access the camera data, and installed the [zed-ros-examples](https://github.com/stereolabs/zed-ros-examples) which allow us to use rviz to visualize data from the camera.

**Comment by wesfletch** [comment]
Closed with 4a3af821d891b5813e01e9ec3a2b49946710cff7
