### ISSUE TITLE
Integration: LiDAR

### ISSUE THREAD

**Issue by wesfletch** [RoboticsClubatUCF/UNTITLED_UGV#16]
Get information from the LiDAR in a ROS-acceptable format (PointCloud2). 

The Velodyne VLP-16 has some network goofery going on with it, so this might require some more effort than the others. And probably some work with Wireshark.

**Comment by marc4813** [comment]
I was able to get the VLP-16 Lidar working with one of the all in ones in the lab. Here's how I did it: 

http://wiki.ros.org/velodyne/Tutorials/Getting%20Started%20with%20the%20Velodyne%20VLP16

I'll try to get the Lidar working on the Jetson next.

**Comment by wesfletch** [comment]
Closed with commit 4a3af821d891b5813e01e9ec3a2b49946710cff7
